language: node_js
node_js: node
services:
  -mongodb
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: bZ42r4hokaXFMfG5xrEkQGz1hLYHF7+iRLqO132RMmxAdzt36Xx7NukSQnG3T1Cy/p8XToWjXoBndQAUzzlSAaLtweG2PULNA7nmEDPywZwyScXtQoktKNB6w/u0rnSfcclFy4nwKe7DflI9xMjtCtB3N028nLVJItM3v+AIR0Dj1SCKSxw5WPGzMAGsCzDlbjCrt3MeN5q+u+WFqbaSzeOIvuWkwiDND8ffGvwrIFb+AYD3Z25bwWnz/Rj1k02kuJhpK3G+cIFUisAsb8a/QpeJliD6KCPwhtghNDvYxWfvE0J4UxQN2u28fl1jfgYo8ZJTxCdqxwvbbEzo8iz/jlYoU5f/Y9B//jZVRVJ+jGH77eXcnTha5kU8gXqZsa759IX2RkUjvlntGzZfFa57cMbbMrQzIxAMklr0Qeyz71T2oI2m7PjzfQJYGkmOnfPhTil3cbh2MdCBVI15J2Dzv0FJ9EzFqoWCVeLKfpLJqHMHKHJOjMIIjDOLeBnAlYHDt+VHqFYdUsks52GNqN05WbDlHNgZL6IyKEFOKRtJDTY9xq356LJFCRzU6VDBYSv6xG78844qivjdwgIbQOjRodmXogkzv5ie9boQN0/Sl86BnJLcz/FozrxZozx3ZcF/QJwc5IYZmGfkJXKjtBjo6lbygovqhNuJX1i7jQsul3o=
  app: secure-coast-72425
  on:
    repo: sretundijr/second-capstone-bill-tracker
